### ISSUE TITLE
Open directory issue

### ISSUE THREAD

**Issue by ITSAIDI** [tzutalin/labelImg#1007]
C:\Users\hp>cd C:\Users\hp\AI\DL formation\Projects\Object recognition.CV\Sign launguage detection\RealTimeObjectDetection\Tensorflow\labelImg

C:\Users\hp\AI\DL formation\Projects\Object recognition.CV\Sign launguage detection\RealTimeObjectDetection\Tensorflow\labelImg>python labelImg.py
Traceback (most recent call last):
  File "C:\Users\hp\AI\DL formation\Projects\Object recognition.CV\Sign launguage detection\RealTimeObjectDetection\Tensorflow\labelImg\labelImg.py", line 1359, in open_dir_dialog
    self.import_dir_images(target_dir_path)
  File "C:\Users\hp\AI\DL formation\Projects\Object recognition.CV\Sign launguage detection\RealTimeObjectDetection\Tensorflow\labelImg\labelImg.py", line 1374, in import_dir_images
    self.open_next_image()
  File "C:\Users\hp\AI\DL formation\Projects\Object recognition.CV\Sign launguage detection\RealTimeObjectDetection\Tensorflow\labelImg\labelImg.py", line 1429, in open_next_image
    self.change_save_dir_dialog()
  File "C:\Users\hp\AI\DL formation\Projects\Object recognition.CV\Sign launguage detection\RealTimeObjectDetection\Tensorflow\labelImg\labelImg.py", line 1309, in change_save_dir_dialog
    self.show_bounding_box_from_annotation_file(self.file_path)
  File "C:\Users\hp\AI\DL formation\Projects\Object recognition.CV\Sign launguage detection\RealTimeObjectDetection\Tensorflow\labelImg\labelImg.py", line 1182, in show_bounding_box_from_annotation_file
    basename = os.path.basename(str(os.path.splitext(file_path))[0])
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 232, in splitext
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by ITSAIDI** [comment]
just restart the labelImg from restart option inside of it

**Comment by TrinhNhatTuyen** [comment]
"File -> Reset All", thank you.
