### ISSUE TITLE
Issue with Semi Automatic Classification Plugin in QGIS - Python error

### ISSUE THREAD

**Issue by elenabalma** [tzutalin/labelImg#1008]
Help! I'm having a problem creating ROIs for a training input in QGIS. I'm using the SCP plugin but Python crashes every time I try ti create a training area ROI by drawing a polygon. I think it's a problem with the source code of the plugin, but I'm not sure. 
The error message is:

WARNING: Traceback (most recent call last):
              File "/Users/elenabalmaceda/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/dock/scpdock.py", line 1736, in pointerClickROI
              self.createROI(cfg.pntROI)
              File "/Users/elenabalmaceda/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/dock/scpdock.py", line 2848, in createROI
              if cfg.np.count_nonzero(r) > 0:
             UnboundLocalError: local variable 'r' referenced before assignment

- **OS: MacOs
- **QGIS version: 3

**Comment by Jaihanumangranite** [comment]
[Italian Marble Suppliers in Delhi](https://www.jhgm.in/italian-marble.html)
[Indian Marble Suppliers](https://www.jhgm.in/indian-marble.html)
[Granite Slab Suppliers](https://www.jhgm.in/granite-slab.html)
[Tiles Suppliers in Delhi](https://www.jhgm.in/tiles.html)
[Kota Marble Suppliers ](https://www.jhgm.in/kota-marble.html)
