### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hz-1** [tzutalin/labelImg#1019]
labelImg.py:73: DeprecationWarning: sipPyTypeDict() is deprecated, the extension module should use sipPyTypeDictRef() instead
  class MainWindow(QMainWindow, WindowMixin):

**Comment by ajeetkr-7** [comment]
I am getting the similar error, I am using Ubuntu 23.10 with PyQt5.
Here is the stacktrace of command `python labelImg.py` (using virtualenv for python3.11)
```
/home/ajeet/Desktop/BTP/labelImg/labelImg.py:73: DeprecationWarning: sipPyTypeDict() is deprecated, the extension module should use sipPyTypeDictRef() instead
  class MainWindow(QMainWindow, WindowMixin):
Traceback (most recent call last):
  File "/home/ajeet/Desktop/BTP/labelImg/labelImg.py", line 1766, in <module>
    sys.exit(main())
                 ^^^^^^
  File "/home/ajeet/Desktop/BTP/labelImg/labelImg.py", line 1761, in main
    app, _win = get_main_app(sys.argv)
                          ^^^^^^^^^^^^^^^^^^^
  File "/home/ajeet/Desktop/BTP/labelImg/labelImg.py", line 1752, in get_main_app
    win = MainWindow(args.image_dir,
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajeet/Desktop/BTP/labelImg/labelImg.py", line 217, in __init__
    self.dock.setFeatures(self.dock.features() ^ self.dock_features)
                                ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for ^: 'DockWidgetFeatures' and 'DockWidgetFeatures'
```
