### ISSUE TITLE
mac os m1 from PyQt5.QtCore import PYQT_VERSION_STR, QDir, QFile

### ISSUE THREAD

**Issue by wscot001** [tzutalin/labelImg#1020]
![image](https://github.com/HumanSignal/labelImg/assets/150100043/0bd92a44-2bb8-4984-bcd9-ffba68ed3d4a)

pyrcc5 -o libs/resources.py resources.qrc
Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/ultralytics/bin/pyrcc5", line 5, in <module>
    from PyQt5.pyrcc_main import main
  File "/Users/a58/anaconda3/envs/ultralytics/lib/python3.12/site-packages/PyQt5/pyrcc_main.py", line 21, in <module>
    from PyQt5.QtCore import PYQT_VERSION_STR, QDir, QFile
ImportError: dlopen(/Users/a58/anaconda3/envs/ultralytics/lib/python3.12/site-packages/PyQt5/QtCore.abi3.so, 0x0002): Symbol not found: __ZTVNSt3__13pmr25monotonic_buffer_resourceE
  Referenced from: <645DDC2C-F655-324A-BE87-40804F3AC471> /Users/a58/anaconda3/envs/ultralytics/lib/python3.12/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore
  Expected in:     <AE8EA4B2-B8FD-33E3-A0AF-0B7485AB97C0> /usr/lib/libc++.1.dylib
make: *** [qt5py3] Error 1

- **OS: mac os m1 13.0.1**
- **PyQt version:5.15.10**

**Comment by YUcxovo** [comment]
try to make a new environment with python version 3.9
