### ISSUE TITLE
unsupported pickle protocol when changing python version

### ISSUE THREAD

**Issue by tzutalin** [tzutalin/labelImg#140]
Traceback (most recent call last):
  File "labelImg.py", line 1325, in <module>
    sys.exit(main(sys.argv))
  File "labelImg.py", line 1321, in main
    app, _win = get_main_app(argv)
  File "labelImg.py", line 1314, in get_main_app
    'data', 'predefined_classes.txt'))
  File "labelImg.py", line 403, in __init__
    self.settings.load()
  File "/home/darrenl/developements/labelImg/libs/settings.py", line 29, in load
    self.data = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 886, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto

- **OS:**  : Swtich python2 <-> python3

**Comment by tzutalin** [comment]
Solution: ` make clean`

**Comment by IdoWSC** [comment]
and for windows?
