### ISSUE TITLE
UnicodeDecodeError during installation. Please replace arrow characters in README.rst

### ISSUE THREAD

**Issue by daewonyoon** [tzutalin/labelImg#235]
failed to install labelimg 1.6.0 using pip to my python 3.6 on windows (non-english). UnicodeDecodeError occurs during file-read operataion on README.rst.

> 
>   readme = readme_file.read()
> 
> UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 5389: illegal multibyte sequence
> 

this might be a bug of the pip ( 9.0.1). however, i could workaround just simply deleting following line and run `setup.py install`.

> | ↑→↓←       | Keyboard arrows to move selected rect box  |

thanx.

**Comment by rockmosi** [comment]
while I was installing labelImg-1.8.4 on windows 10, it shows the error.

ERROR: Command errored out with exit status 1:
     command: 'C:\Users\rock\.conda\envs\tf23gpu\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\rock\\AppData\\Local\\Temp\\pip-install-t51kp22v\\labelimg_9e4dc22f8ffe4ff99acef878227572f6\\setup.py'"'"'; __file__='"'"'C:\\Users\\rock\\AppData\\Local\\Temp\\pip-install-t51kp22v\\labelimg_9e4dc22f8ffe4ff99acef878227572f6\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\rock\AppData\Local\Temp\pip-pip-egg-info-jalt1z5g'
         cwd: C:\Users\rock\AppData\Local\Temp\pip-install-t51kp22v\labelimg_9e4dc22f8ffe4ff99acef878227572f6\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\rock\AppData\Local\Temp\pip-install-t51kp22v\labelimg_9e4dc22f8ffe4ff99acef878227572f6\setup.py", line 20, in <module>
        readme = readme_file.read()
    UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 7520: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by daewonyoon** [comment]
> while I was installing labelImg-1.8.4 on windows 10, it shows the error.
> python ver: 3.7.0
> 
> ERROR: Command errored out with exit status 1:
> command: 'C:\Users\rock.conda\envs\tf23gpu\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\rock\AppData\Local\Temp\pip-install-t51kp22v\labelimg_9e4dc22f8ffe4ff99acef878227572f6\setup.py'"'"'; **file**='"'"'C:\Users\rock\AppData\Local\Temp\pip-install-t51kp22v\labelimg_9e4dc22f8ffe4ff99acef878227572f6\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\rock\AppData\Local\Temp\pip-pip-egg-info-jalt1z5g'
> cwd: C:\Users\rock\AppData\Local\Temp\pip-install-t51kp22v\labelimg_9e4dc22f8ffe4ff99acef878227572f6
> Complete output (5 lines):
> Traceback (most recent call last):
> File "", line 1, in
> File "C:\Users\rock\AppData\Local\Temp\pip-install-t51kp22v\labelimg_9e4dc22f8ffe4ff99acef878227572f6\setup.py", line 20, in
> readme = readme_file.read()
> UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 7520: illegal multibyte sequence
> ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

 - download labelimg tar gz file.
 - unzip
 - edit setup.py line 19 : `open('README.rst')` to `open('README.rst', encoding='utf-8')`
 - in unzip directory execute pip install command `pip install . `

**Comment by rockmosi** [comment]
> * download labelimg tar gz file.
> * unzip
> * edit setup.py line 19 : `open('README.rst')` to `open('README.rst', encoding='utf-8')`
> * in unzip directory execute pip install command `pip install . `

wow thank you
this is working like charm.

+ I saw error. No module named 'libs.resources'
the solution is this.
https://github.com/tzutalin/labelImg/issues/475
after this cmd,
pyrcc5 -o libs/resources.py resources.qrc
I reinstall labelImg, and then working fine.

**Comment by KSneijders** [comment]
To put it all in one post: 

> download labelimg tar gz file.
> unzip
> edit setup.py line 19 : `open('README.rst')` to `open('README.rst', encoding='utf-8')`
> in unzip directory execute pip install command `pip install .`

After that, in that directory, execute: (Like @rockmosi said)

> Please try this command from labelImg directory `pyrcc5 -o libs/resources.py resources.qrc`
