### ISSUE TITLE
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class

### ISSUE THREAD

**Issue by yishen-zhao** [tzutalin/labelImg#268]
File "/home/yishen/labelImg-master/resources.py", line 9, in <module>
    from PyQt4 import QtCore
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class

I don't install pyqt5

**Comment by rcgatto** [comment]
Hi,
I have PyQt5. I suggest install PyQt5 and change any reference of PyQt4 to PyQt5 in resources.py and in ./libs/ustr.py. 
You will have an error like "ImportError: cannot import name QString" in ustr.py. Just change the line 
      if type(x) == QString:
to
      if type(x) == type('string'):

**Comment by rcgatto** [comment]
Hi,

I'm using Python 2.7 in Ubuntu 16.4

Rubens

2018-05-26 18:23 GMT-03:00 vdalv <notifications@github.com>:

**Comment by osxn** [comment]
how to solve this problem. didn't find any soulution in #212.

**Comment by osxn** [comment]
meet the same problem.

**Comment by osxn** [comment]
when I uninstall pyqt4 and use pyqt5 instead,

Traceback (most recent call last):
  File "labelImg.py", line 1456, in <module>
    sys.exit(main())
  File "labelImg.py", line 1452, in main
    app, _win = get_main_app(sys.argv)
  File "labelImg.py", line 1445, in get_main_app
    argv[3] if len(argv) >= 4 else None)
  File "labelImg.py", line 98, in __init__
    self.settings.load()
  File "/home/enjoy-life/labelImg/libs/settings.py", line 33, in load
    self.data = pickle.load(f)
ImportError: No module named 'PyQt4'

**Comment by vdalv** [comment]
@osxn Run this command: `pyrcc5 -o resources.py resources.qrc`

**Comment by rkachach** [comment]
I faced the same issue (I'm using pyqt5). Basically it seems that in qt5 there's no class called string. I used the following workaround in libs/ustr.py and it worked fine:

```
try:
    from PyQt4.QtCore import QString  
except ImportError:
    # we are using Python3 so QString is not defined
    QString = str
```
This way, when using qt5 you switch to python string instead of QString.

**Comment by bessszilard** [comment]
If you installed qt5, try to run with python3:
```$ python3 labelImg.py```

**Comment by Lanme** [comment]
I used the code from rkachach ,but error still unsolved. I realize that it's not an improrerror,so after remove the importerror ,it works.
