### ISSUE TITLE
Opens and closes

### ISSUE THREAD

**Issue by wajahat57** [tzutalin/labelImg#282]
Hi
When you run this application and annotate images in a particular folder. Afterwards, if you close this app and delete the folder, the app will crash.
Please fix this error.

`C:\Program Files\Label_IM_windows_v1.5.0>labelImg
Traceback (most recent call last):
  File "<string>", line 1327, in <module>
  File "<string>", line 1323, in main
  File "<string>", line 1316, in get_main_app
  File "<string>", line 403, in __init__
  File "Z:\home\darrenl\tmp\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\libs.settings", line 30, in load
  File "Z:\home\darrenl\tmp\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\pickle", line 1378, in load
  File "Z:\home\darrenl\tmp\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\pickle", line 858, in load
  File "Z:\home\darrenl\tmp\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\pickle", line 880, in load_eof
EOFError`

Although deleting .labelImgSettings.pkl file in the C:\users\username\ 
solves this for v.1.6.0.

- **OS:** Windows 10 x64
- **PyQt version:**

**Comment by wajahat57** [comment]
OK. found it for v.1.5.0. 
deleting the settings.pkl file in the folder of labelImg.exe solves this problem.
