### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'toggleVerify'

### ISSUE THREAD

**Issue by bradleyrobinson** [tzutalin/labelImg#287]
When clicking the verify image box, if I cancel rather than selecting save the program closes with the error:
```
Traceback (most recent call last):
  File "labelImg.py", line 1173, in verifyImg
    self.labelFile.toggleVerify()
AttributeError: 'NoneType' object has no attribute 'toggleVerify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "labelImg.py", line 1178, in verifyImg
    self.labelFile.toggleVerify()
AttributeError: 'NoneType' object has no attribute 'toggleVerify'
Aborted (core dumped)

```
Looks like there needs to be a check to make sure that labelFile is not None. I would be happy to make a pull request to fix this issue.
- Ubuntu 16.04 LTS
- PyQT5

**Comment by vdalv** [comment]
This issue should be resolved now. Thanks for bringing it to our attention.
