### ISSUE TITLE
App crash when drag a corner of rectbox to border of image

### ISSUE THREAD

**Issue by zeuspnt** [tzutalin/labelImg#323]
Below is output when app crash.

```
Traceback (most recent call last):
  File "/Users/admin/Desktop/ML/Tools/labelImg/libs/canvas.py", line 152, in mouseMoveEvent
    self.boundedMoveVertex(pos)
  File "/Users/admin/Desktop/ML/Tools/labelImg/libs/canvas.py", line 321, in boundedMoveVertex
    pos = self.intersectionPoint(point, pos)
  File "/Users/admin/Desktop/ML/Tools/labelImg/libs/canvas.py", line 499, in intersectionPoint
    d, i, (x, y) = min(self.intersectingEdges((x1, y1), (x2, y2), points))
ValueError: min() arg is an empty sequence
Abort trap: 6
```

**Comment by vdalv** [comment]
I'm not experiencing this issue myself... Are you using the latest version of labelImg?

Also, what OS are you using? and how are you running labelImg (from source or binary)?

**Comment by vdalv** [comment]
@zeuspnt Did you follow the 'Python 3 + Qt5 (Works on macOS High Sierra)' instructions [here](https://github.com/tzutalin/labelImg#macos)?

**Comment by zeuspnt** [comment]
I follow this 'NEW Python 3 Virtualenv + Binary'

**Comment by vdalv** [comment]
Ah, I recommend following the 'Python 3 + Qt5' instructions, as the Virtualenv + Binary installation is buggy (our last three issues were related to it).

**Comment by lgov** [comment]
I'm guessing pull request #414 solves this issue.

**Comment by mcsimenc** [comment]
I'm using Python 3 + Qt5 and labelImg crashes with the same error as originally reported here
