### ISSUE TITLE
Crashes on open image annotation file

### ISSUE THREAD

**Issue by banderlog** [tzutalin/labelImg#341]
It  crashes with qt5py3 build from `git clone`, and releases `1.7.0`,  `1.6.0`, `1.5.0`.

Deleting  `~/.labelImageSetting.pkl ` did not  solve the problem.

**Error logs:**
From 1.6.0:
```
Traceback (most recent call last):
  File "./labelImg.py", line 1194, in openFile
    self.loadFile(filename)
  File "./labelImg.py", line 923, in loadFile
    self.lineColor = QColor(*self.labelFile.lineColor)
AttributeError: 'LabelFile' object has no attribute 'lineColor'
Aborted
```

From 1.7.0:
```
Traceback (most recent call last):
  File "./labelImg.py", line 1261, in openFile
    self.loadFile(filename)
  File "./labelImg.py", line 976, in loadFile
    self.lineColor = QColor(*self.labelFile.lineColor)
AttributeError: 'LabelFile' object has no attribute 'lineColor'
Aborted
```

From latest git version:
```
Traceback (most recent call last):
  File "./labelImg.py", line 1264, in openFile
    self.loadFile(filename)
  File "./labelImg.py", line 976, in loadFile
    self.lineColor = QColor(*self.labelFile.lineColor)
AttributeError: 'LabelFile' object has no attribute 'lineColor'
Aborted
```

From 1.5.0:
```
Traceback (most recent call last):
  File "./labelImg.py", line 1153, in openFile
    self.loadFile(filename)
  File "./labelImg.py", line 896, in loadFile
    self.lineColor = QColor(*self.labelFile.lineColor)
AttributeError: 'LabelFile' object has no attribute 'lineColor'
Aborted
```

OS: Gentoo x86_64
PyQt5: 5.9.2

**Comment by banderlog** [comment]
Well, the problem was from my side, however it is pretty strange) 

I accidentaly spotted that qt does not allow me to open `jpg` files, so I've checked my emerge log and it appears that I built `dev-qt/qtgui` without `jpeg` USE-flag.  I've reemerged `dev-qt/qtgui` with it and problem disappeared.

Maybe, it will help someone.

**Comment by vdalv** [comment]
Cool, thanks for the update.
