### ISSUE TITLE
Bug executing `labelImg` with different python versions

### ISSUE THREAD

**Issue by juliusHuelsmann** [tzutalin/labelImg#343]
By using the `labelImg` tool both with python2 and python3, I spotted the following bug ...

```bash
Traceback (most recent call last):
  File "labelImg.py", line 1459, in <module>
    sys.exit(main())
  File "labelImg.py", line 1455, in main
    app, _win = get_main_app(sys.argv)
  File "labelImg.py", line 1448, in get_main_app
    argv[3] if len(argv) >= 4 else None)
  File "labelImg.py", line 101, in __init__
    self.settings.load()
  File "/mnt/data/online/repos/dataspree/labelImage/labelImg/libs/settings.py", line 33, in load
    self.data = pickle.load(f)
ModuleNotFoundError: No module named 'PyQt4'
```

... that is caused by the Config file (at `~/.labelImgSettings.pkl`) storing the dependencies used during the first execution. When using a different python version now (that has not qt4 installed), loading throws the aforementioned `module not found error`. Therefore I propose to 
1. encode the version under which the configuration was created inside the name of the file (distinction qt4/5 or python 2/3 should suffice).
2. notify the user on the fact that there are multiple configuration files

**Comment by zhaoxuyan** [comment]
### For Windows
Go to `Users\xxx\` delete `.labelImgSettings.pkl`,then `pyrcc5 -o libs/resources.py resources.qrc`, `python labelImg.py`
### For Mac or Linux
Go to home(~) folder, `rm .labelImgSettings.pkl`, then `pyrcc5 -o libs/resources.py resources.qrc`, `python labelImg.py`

**Comment by mkrupczak3** [comment]
If the pyrcc5 command doesn't work, run the following first:
`pip install --force-reinstall PyQt5-sip`
