### ISSUE TITLE
Execute labelImg Error

### ISSUE THREAD

**Issue by donconfucian** [tzutalin/labelImg#370]
os: Windows
env: Anaconda 4.5.4 , 
       py3.5,
       pyqt 5.6

(py3.5) >labelImg
Traceback (most recent call last):
  File "d:\program_files\anaconda\envs\py3.5\lib\runpy.py", line 193, in _run_mo
dule_as_main
    "__main__", mod_spec)
  File "d:\program_files\anaconda\envs\py3.5\lib\runpy.py", line 85, in _run_cod
e
    exec(code, run_globals)
  File "D:\Program_Files\Anaconda\envs\py3.5\Scripts\labelImg.exe\__main__.py",
line 9, in <module>
  File "d:\program_files\anaconda\envs\py3.5\lib\site-packages\labelImg\labelImg
.py", line 1449, in main
    app, _win = get_main_app(sys.argv)
  File "d:\program_files\anaconda\envs\py3.5\lib\site-packages\labelImg\labelImg
.py", line 1442, in get_main_app
    argv[3] if len(argv) >= 4 else None)
  File "d:\program_files\anaconda\envs\py3.5\lib\site-packages\labelImg\labelImg
.py", line 98, in __init__
    self.settings.load()
  File "d:\program_files\anaconda\envs\py3.5\lib\site-packages\libs\settings.py"
, line 33, in load
    self.data = pickle.load(f)
EOFError: Ran out of input

**Comment by tzutalin** [comment]
Will fix in next windows' binary release
