### ISSUE TITLE
from PyQt5.QtCore import PYQT_VERSION_STR, QDir, QFile ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Poonamjo** [tzutalin/labelImg#413]
when I am running the command pyrcc5 -o resources.py resources.qrc i am getting the error 

Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\lib\site-packages\PyQt5\pyrcc_main.py", line 21, in <module>
    from PyQt5.QtCore import PYQT_VERSION_STR, QDir, QFile
ImportError: DLL load failed: The specified module could not be found.
- **OS: Windows**
- **PyQt version:pyqt5**

**Comment by Hutch07** [comment]
I have the same thing on a Windows 10 machine.  Can you suggest which setting to look at in Qt?

**Comment by HonzaAus** [comment]
Same here. Anyone solved this?

**Comment by vdevakko** [comment]
I'm facing the same issue. Kindly need support. Thanks!

---
(tf_0002) C:\001_DLPC_PROJECTS\TensorFlow\addons\labelImg>pyrcc5 -o libs/resources.py resources.qrc
Traceback (most recent call last):
  File "C:\Users\DLPC\Anaconda3\envs\tf_0002\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\DLPC\Anaconda3\envs\tf_0002\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\DLPC\Anaconda3\envs\tf_0002\lib\site-packages\PyQt5\pyrcc_main.py", line 21, in <module>
    from PyQt5.QtCore import PYQT_VERSION_STR, QDir, QFile
ImportError: DLL load failed: The specified module could not be found.
---

**Comment by sarathy86** [comment]
I have installed PyQt4 and ran the same command it worked!!

**Comment by adrianaksan** [comment]
Try: **pip3 install pyqt5**

**Comment by Abhipray04** [comment]
It is because of missing Python3.dll (stub dll, that re-exports Python3x.dll functions, so that one version of extension can work for multiple versions of python).

If your Python distro doesn't bundle python3.dll, you can try one from WinPython (https://winpython.github.io/).

At least the 2017/04/01 versions should have it.

1) Download WinPython ('Zero' version suffices; must be same "main version" - 3.5/3.6 -and "bitness" - 32/64 - as your Python !!!).

2) Extract to some temp directory, take the python3.dll and stick it into your python dir, next to the python3x.dll.

3) Also, to make sure, paste the Python3.dll and Python3x.dll files to your labelImg directory.

4) Enjoy working QT

**Comment by SangeethRaajA** [comment]
when I am running the command `pyrcc5 -o resources.py resources.qrc` i got the same error and solved it using the below step

i uninstalled PyQt5 and reinstalled it
`python -m pip uninstall PyQt5` 
`python -m pip install PyQt5`

copied the path given by as warning and replaced in front of pyrcc5 as the path and it worked perfectly

C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\pyrcc5 -o libs/resources.py resources.qrc

**Comment by kimimccaw** [comment]
Hello I am still new to python and pyqt5

I tried to run "pyuic5 -x test.ui -o test.py" on cmd but i got an error(below).

AttributeError: module 'PyQt5.bindings.QtCore' has no attribute 'PYQT_VERSION_STR'

**Comment by javgarces** [comment]
I got this issue when working on a folder with restricted permissions (I'm working on a university-owned computer with some access restrictions).

I created a virtual environment on a folder where I didn't have that issue, reinstalled everything there, and the pyrcc5 command worked there.

**Comment by nikeshdevkota** [comment]
The issue seems to be due to the pyqt5 version. I just uninstalled the latest version of pyqt5 and installed pyqt 5.12.3 and labelIng worked. I had also put python3.dll inside labelImg folder.
