### ISSUE TITLE
I found a spelling error, It will cause output “Invalid locale” in windows

### ISSUE THREAD

**Issue by shijie001** [tzutalin/labelImg#428]
commit c2aca6e 

diff --git a/libs/stringBundle.py b/libs/stringBundle.py
index 6cbc3e4..ba41aa9 100644
--- a/libs/stringBundle.py
+++ b/libs/stringBundle.py
@@ -35,7 +35,7 @@ class StringBundle:
                     locale.getlocale()) > 0 else os.getenv('LANG')
             except:
                 print('Invalid locale')
-                locale = 'en'
+                localeStr = 'en'
         return StringBundle(cls.__create_key, localeStr)

**Comment by RRoundTable** [comment]
I also found 'Invalid locale' issue. How can I solve this problem?

Invalid locale
Traceback (most recent call last):
  File "labelImg.py", line 1483, in <module>
    sys.exit(main())
  File "labelImg.py", line 1479, in main
    app, _win = get_main_app(sys.argv)
  File "labelImg.py", line 1472, in get_main_app
    argv[3] if len(argv) >= 4 else None)
  File "labelImg.py", line 130, in __init__
    self.useDefaultLabelCheckbox = QCheckBox(getStr('useDefaultLabel'))
  File "labelImg.py", line 95, in <lambda>
    getStr = lambda strId: self.stringBundle.getString(strId)
  File "C:\Users\ryu07\OneDrive\sourceCode\object_detection\labelImg\libs\stringBundle.py", line 42, in getString
    assert(stringId in self.idToMessage), "Missing string id : " + stringId
AssertionError: Missing string id : useDefaultLabel
