### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by LukeAI** [tzutalin/labelImg#433]
Ubuntu 16.04 Python 3 + Qt5

To reproduce: Clone repo. cd into it, follow install instructions:

sudo apt-get install pyqt5-dev-tools
sudo pip3 install -r requirements/requirements-linux-python3.txt
make qt5py3

```
luke@AIDlaptop2:~/labelImg$ sudo pip3 install -r requirements/requirements-linux-python3.txt
The directory '/home/luke/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/luke/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): pyqt5==5.10.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements/requirements-linux-python3.txt (line 1))
Collecting lxml==4.2.4 (from -r requirements/requirements-linux-python3.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/9e/3a/32438b5b54d2c13a9be88d2718b108eb6f3eb501fc68726b9faadebae160/lxml-4.2.4-cp35-cp35m-manylinux1_x86_64.whl (5.8MB)
    100% |████████████████████████████████| 5.8MB 287kB/s 
Requirement already satisfied (use --upgrade to upgrade): sip<4.20,>=4.19.4 in /usr/local/lib/python3.5/dist-packages (from pyqt5==5.10.1->-r requirements/requirements-linux-python3.txt (line 1))
Installing collected packages: lxml
  Found existing installation: lxml 3.5.0
    Not uninstalling lxml at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed lxml-3.5.0
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
luke@AIDlaptop2:~/labelImg$ make qt5py3
pyrcc5 -o resources.py resources.qrc
Traceback (most recent call last):
  File "/usr/local/bin/pyrcc5", line 7, in <module>
    from PyQt5.pyrcc_main import main
ImportError: No module named 'PyQt5.pyrcc_main'
Makefile:24: recipe for target 'qt5py3' failed
make: *** [qt5py3] Error 1
```

**Comment by DeepPower** [comment]
I have the same problem.

**Comment by tzutalin** [comment]
Could you try do again and run those command ahead of time
```
sudo pip3 install pyblake2
sudo apt-get install pyqt5-dev pyqt5-dev-tools
```

**Comment by LukeAI** [comment]
Thanks for response, will do so soon - is there a reason why it's **sudo** pip? This is generally not advised?

**Comment by LukeAI** [comment]
@tzutalin 

pyqt5-dev pyqt5-dev-tools were already installed. I just recloned and tried to get the python2 version going:

```
$ make qt4py2
pyrcc4 -py2 -o resources.py resources.qrc
luke@AIDlaptop2:~/labelImg$ python labelImg.py 
Traceback (most recent call last):
  File "labelImg.py", line 29, in <module>
    import resources
  File "/home/luke/labelImg/resources.py", line 9, in <module>
    from PyQt4 import QtCore
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
```

However, it now works with python3 :)
