### ISSUE TITLE
Cannot start binary on Ubuntu

### ISSUE THREAD

**Issue by swiss-knight** [tzutalin/labelImg#440]
I cannot start the binary on Ubuntu 18.04.
Here is the error:

```
$ labelImg 
Traceback (most recent call last):
  File "/usr/local/bin/labelImg", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/labelImg/labelImg.py", line 1473, in main
    app, _win = get_main_app(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/labelImg/labelImg.py", line 1466, in get_main_app
    argv[3] if len(argv) >= 4 else None)
  File "/usr/local/lib/python3.6/dist-packages/labelImg/labelImg.py", line 130, in __init__
    self.useDefaultLabelCheckbox = QCheckBox(getStr('useDefaultLabel'))
  File "/usr/local/lib/python3.6/dist-packages/labelImg/labelImg.py", line 95, in <lambda>
    getStr = lambda strId: self.stringBundle.getString(strId)
  File "/usr/local/lib/python3.6/dist-packages/libs/stringBundle.py", line 36, in getString
    assert(stringId in self.idToMessage), "Missing string id : " + stringId
AssertionError: Missing string id : useDefaultLabel
```

- **OS:** Ubuntu 18.04 64 bits
- **PyQt version:**  5.11.3 

labelImg was installed from pypi repo.

**Comment by giker17** [comment]
I encountered the same question on ubuntu 16.04.

- pyqt: 5.10.1
- lxml: 4.2.4

**Comment by fgsalomon** [comment]
You have to generate the resources with:
```bash
pyrcc5 resources.qrc -o resources.py
```

**Comment by 2276022686** [comment]
> You have to generate the resources with:
> 
> ```shell
> pyrcc5 resources.qrc -o resources.py
> ```

ThankU ,i have got it ,but what is the reason

**Comment by fgsalomon** [comment]
String translations are stored as Qt resources and they must be converted beforehand to Python modules so they can be imported. I guess they should update the [instructions](https://github.com/tzutalin/labelImg#get-from-pypi) on the README file.

**Comment by 2276022686** [comment]
> String translations are stored as Qt resources and they must be converted beforehand to Python modules so they can be imported. I guess they should update the [instructions](https://github.com/tzutalin/labelImg#get-from-pypi) on the README file.

yeah,thanks for your reply,i've gor it
