### ISSUE TITLE
mac 编译失败

### ISSUE THREAD

**Issue by xuange306** [tzutalin/labelImg#536]
- **OS: 10.15.1**
- **PyQt version: pyqt5**
- **Python version: 3.7.5:**

mac 编译报错
我执行下列命令:
~~~
git clone https://github.com/tzutalin/labelImg.git
cd labelImg
pip3 install pyqt5 lxml
make qt5py3              #这里报错了
~~~

错误如下
~~~
$ make qt5py3
pyrcc5 -o libs/resources.py resources.qrc
Traceback (most recent call last):
  File "/usr/local/bin/pyrcc5", line 7, in <module>
    from PyQt5.pyrcc_main import main
  File "/usr/local/lib/python3.7/site-packages/PyQt5/pyrcc_main.py", line 23, in <module>
    from .pyrcc import *
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/PyQt5/pyrcc.abi3.so, 2): Library not loaded: @rpath/QtXml.framework/Versions/5/QtXml
  Referenced from: /usr/local/lib/python3.7/site-packages/PyQt5/pyrcc.abi3.so
  Reason: image not found
make: *** [qt5py3] Error 1
~~~

**Comment by tzutalin** [comment]
Hi,
The latest pyqt has an issue.
Try the previous version: 

pip install pyqt5==5.13.2

**Comment by dlopezabril** [comment]
Thanks for your help.
After many attemps, pip install pyqt5==5.13.2 works on my MAC with a virtual env
