### ISSUE TITLE
Question: How to fix  ImportError: DLL load failed: The specified procedure could not be found. Windows + Anaconda

### ISSUE THREAD

**Issue by okoliechykwuka** [tzutalin/labelImg#564]
**Here is what I have done so far to setup LabelImg**

**Windows + Anaconda**
Install Python, PyQt5 and install lxml
git clone https://github.com/tzutalin/labelImg

I then had to moved to the  **labelImg** directory using cd labelImg

Next, pyrcc5 -o libs/resources.py resources.qrc

**Here come the error response**

`(base) C:\Users\8470p\labelImg>pyrcc5 -o libs/resources.py resources.qrc
Traceback (most recent call last):
  File "C:\Users\8470p\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\8470p\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\8470p\Anaconda3\lib\site-packages\PyQt5\pyrcc_main.py", line 23, in <module>
    from .pyrcc import *
ImportError: DLL load failed: The specified procedure could not be found.
`

**Comment by sunh0003** [comment]
I run into the same error. I tried many different things but all failed. Eventually i did conda update --all, and it solved the problem. hope this helps.
