### ISSUE TITLE
labelimg.exe generate ValueError: unsupported pickle protocol: 4

### ISSUE THREAD

**Issue by Sam7791** [tzutalin/labelImg#574]
- **OS: Windows 10**
- **PyQt version:**

**Comment by Sam7791** [comment]
Hello,
I get this error when I execute labelImge.exe version 1.8.0 with python 3.6.5 installed:
Traceback (most recent call last):
  File "<string>", line 1478, in <module>
  File "<string>", line 1474, in main
  File "<string>", line 1467, in get_main_app
  File "<string>", line 98, in __init__
  File "Z:\home\darrenl\tmp\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\libs.settings", line 33, in load
  File "Z:\home\darrenl\tmp\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\pickle", line 1378, in load
  File "Z:\home\darrenl\tmp\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\pickle", line 858, in load
  File "Z:\home\darrenl\tmp\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\pickle", line 886, in load_proto
ValueError: unsupported pickle protocol: 4

**Comment by sunxirui310** [comment]
same error!

**Comment by SB2020-eye** [comment]
Same here
