### ISSUE TITLE
ImportError: No module named download using pipenv

### ISSUE THREAD

**Issue by khanhtran2000** [tzutalin/labelImg#637]
I'm following the "Python 3 Virtualenv (Recommend)" steps. After successfully running ```pip3 install pipenv```, I ran into an error while trying to run ```pipenv run pip install pyqt5==5.13.2 lxml```. Here is the error:
```
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File "/Users/macbook/Library/Python/2.7/lib/python/site-packages/pipenv/__init__.py", line 23, in <module>
    from .cli import cli
  File "/Users/macbook/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 26, in <module>
    from .utils import is_valid_url
  File "/Users/macbook/Library/Python/2.7/lib/python/site-packages/pipenv/utils.py", line 59, in <module>
    from .vendor.requirementslib import Requirement
  File "/Users/macbook/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/requirementslib/__init__.py", line 6, in <module>
    from .models import Requirement, Lockfile, Pipfile
  File "/Users/macbook/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/requirementslib/models/__init__.py", line 8, in <module>
    from .requirements import Requirement
  File "/Users/macbook/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 15, in <module>
    from .markers import PipenvMarkers
  File "/Users/macbook/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 6, in <module>
    from .utils import validate_markers, filter_none
  File "/Users/macbook/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/requirementslib/models/utils.py", line 9, in <module>
    from .._compat import Link
  File "/Users/macbook/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/requirementslib/_compat.py", line 46, in <module>
    is_file_url = do_import("download", "is_file_url")
  File "/Users/macbook/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/requirementslib/_compat.py", line 35, in do_import
    _tmp = importlib.import_module(pip9)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named download
```
I have googled this error but it doesn't seem to help. Has anyone run into this error and what was your solution? Many thanks.

- **OS: macOS Catalina**
- **PyQt version: PyQt5**

**Comment by niwanski** [comment]
Looks like you may want to ensure everything is up to date and linked properly. 

Try running:
`pip install --upgrade --user pipenv`
