### ISSUE TITLE
Unable to open previously saved .xml file

### ISSUE THREAD

**Issue by zoehako** [tzutalin/labelImg#666]
- **OS: Mac
- **PyQt version: 5.15.1
- Python 3.8.6 Homebrew

Python crashes and this error appears when i "Open Dir > .xml file"

Traceback (most recent call last):
  File "labelimg.py", line 1367, in openFile
    self.loadFile(filename)
  File "labelimg.py", line 1065, in loadFile
    self.lineColor = QColor(*self.labelFile.lineColor)
AttributeError: 'LabelFile' object has no attribute 'lineColor'
zsh: abort      python labelimg.py

**Comment by EpochalEngineer** [comment]
Also having this issue when opening an annotation directly. #341 and #210 did not work for me either.

I opened up a debugger and the [initialization call to labelFile](https://github.com/tzutalin/labelImg/blob/master/libs/labelFile.py#L35) does not do anything with the [filename](https://github.com/tzutalin/labelImg/blob/master/labelImg.py#L1056), so it's obvious why there's no lineColor attribute or imageData. I'm guessing this workflow hasn't been exercised recently, and most just open a directory? 

Opening a directory doesn't seem to work in my case. Note that I am just trying to open existing pascal labels, and the labels are in a different directory from the images (but referred to correctly via pascal VOC path attribute)

**Comment by Derekabc** [comment]
see the script to change the file names in the XML files.[link](https://github.com/Derekabc/Icon_detector/blob/master/utils/xml_hander.py)

**Comment by SamuelMarks** [comment]
Band-aid solution:
```py
self.line_color = QColor(*self.label_file.lineColor) if hasattr(self.label_file, "lineColor") else DEFAULT_LINE_COLOR
self.fill_color = QColor(*self.label_file.fillColor) if hasattr(self.label_file, "fillColor") else DEFAULT_FILL_COLOR
```

…but yeah [still TODO:] need to cycle through the different colours and map them properly I think.
