### ISSUE TITLE
 UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 7531: character maps to <undefined>

### ISSUE THREAD

**Issue by austinulfers** [tzutalin/labelImg#676]
Attempting to use `pip install labelimg` to install on Python 3.8.6. I am using a virtual environment and am getting the below error.

- **OS: Windows 10**
- **Python: 3.8.6**
- **PyQt version: 5.15.2**

```
$ pip install labelimg
Collecting labelimg
  Using cached labelImg-1.8.4.tar.gz (242 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\austi\onedrive\git-projects\spikeball-tracking\env\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\austi\\AppData\\Local\\Temp\\pip-install-a0vzp33l\\labelimg\\setup.py'"'"'; __file__='"'"'C:\\Users\\austi\\AppData\\Local\\Temp\\pip-install-a0vzp33l\\labelimg\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\austi\AppData\Local\Temp\pip-pip-egg-info-4u2c3q40'
         cwd: C:\Users\austi\AppData\Local\Temp\pip-install-a0vzp33l\labelimg\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\austi\AppData\Local\Temp\pip-install-a0vzp33l\labelimg\setup.py", line 20, in <module>
        readme = readme_file.read()
      File "C:\Python\Python38\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 7531: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Chagui-** [comment]
I think its version 1.8.4. Installing previous version worked for me.
`pip install labelImg==1.8.3`

**Comment by austinulfers** [comment]
Yup, that was it. Thank you, closing the issue now.

**Comment by Chagui-** [comment]
But i think this still is a bug. I was reading about the error, and it may be because setup.py is importing the readme file which has some unicode stuff in it. Or something related to that.

**Comment by AntonSax** [comment]
This is definitely still a bug as I'm receiving this error on my own machine.

**Comment by Razikus** [comment]
Still a bug

**Comment by owlg** [comment]
Remains a bug that is still unfixed, and happens when I am using .read()

**Comment by Denbergvanthijs** [comment]
I hope my PR will fix this
