### ISSUE TITLE
Unable to open default EUDC font

### ISSUE THREAD

**Issue by Dragon201701** [tzutalin/labelImg#690]
- **OS:**
- **PyQt version:**

qt.qpa.fonts: Unable to open default EUDC font: "C:\\Users\\yz-li\\AppData\\Loca lLow\\SogouPY\\EUDC\\SGPYEUDC_1.TTE"                                             Traceback (most recent call last):                                                 File "labelImg.py", line 1606, in                                          sys.exit(main())                                                               File "labelImg.py", line 1602, in main                                             app, _win = get_main_app(sys.argv)                                             File "labelImg.py", line 1593, in get_main_app                                     win = MainWindow(args.image_dir,                                               File "labelImg.py", line 216, in __init__                                          copyPrevBounding = action(getStr('copyPrevBounding'), self.copyPreviousBound ingBoxes,                                                                          File "labelImg.py", line 88, in                                            getStr = lambda strId: self.stringBundle.getString(strId)                      File "D:\labelImg\libs\stringBundle.py", line 42, in getString                     assert(stringId in self.idToMessage), "Missing string id : " + stringId      AssertionError: Missing string id : copyPrevBounding
--

**Comment by Dragon201701** [comment]
跟搜狗拼音貌似没关系，我把文件名改了或者整个文件夹删了貌似都没用，错误还在。

**Comment by zerovirus123** [comment]
Second this. How did the code update break self.string_bundle.get_string() in the MainWindow?
