### ISSUE TITLE
ModuleNotFoundError: No module named 'lxml'

### ISSUE THREAD

**Issue by SidMalladi** [tzutalin/labelImg#692]
python3 labelImg.py

Traceback (most recent call last):
  File "labelImg.py", line 41, in <module>
    from libs.labelFile import LabelFile, LabelFileError, LabelFileFormat
  File "/Users/sm/Desktop/research/RealTimeObjectDetection/Tensorflow/labelImg/libs/labelFile.py", line 10, in <module>
    from libs.pascal_voc_io import PascalVocWriter
  File "/Users/sm/Desktop/research/RealTimeObjectDetection/Tensorflow/labelImg/libs/pascal_voc_io.py", line 6, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'

I previously had PyQt5 and sip command errors which I had solved following the other threads, I'll be really grateful if someone guides me well on this issue!

- **OS:** MacOS Catalina 10.15.3
- **PyQt version:** 5

**Comment by ChinUSA** [comment]
"pip3 install lxml" fixed it for me
