### ISSUE TITLE
Having trouble installing labelImg on ubuntu 20.04

### ISSUE THREAD

**Issue by elztu** [tzutalin/labelImg#713]
In tried installing via _pip3 install labelImg_ in a virtual environment. The installation went fine but when I went to run _labelImg_ I received this error:
____________________________________________
Traceback (most recent call last):
  File "/home/****.virtualenvs/lablez/lib/python3.8/site-packages/labelImg/labelImg.py", line 16, in <module>
    from PyQt5.QtGui import *
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/****/.virtualenvs/lablez/lib/python3.8/site-packages/PyQt5/QtGui.abi3.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/****/.virtualenvs/lablez/bin/labelImg", line 5, in <module>
    from labelImg.labelImg import main
  File "/home/****/.virtualenvs/lablez/lib/python3.8/site-packages/labelImg/labelImg.py", line 25, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'

____________________________________________    
    

Any ideas?

- **OS: Ubuntu 20.04
- **PyQt version: 5

**Comment by smartadpole** [comment]
pip install sip
pip install PyQt5-sip

**Comment by elztu** [comment]
Thanks @smartadpole, but still got the same error message.
