### ISSUE TITLE
save problem

### ISSUE THREAD

**Issue by lyd959** [tzutalin/labelImg#746]
Traceback (most recent call last):
  File "labelImg.py", line 1382, in save_file
    self._save_file(saved_path)
  File "labelImg.py", line 1414, in _save_file
    if annotation_file_path and self.save_labels(annotation_file_path):
  File "labelImg.py", line 856, in save_labels
    self.label_file.save_yolo_format(annotation_file_path, shapes, self.file_path, self.image_data, self.label_hist,
  File "/home/lyd/pyHub/labelImg/libs/labelFile.py", line 112, in save_yolo_format
    writer.save(target_file=filename, class_list=class_list)
  File "/home/lyd/pyHub/labelImg/libs/yolo_io.py", line 64, in save
    out_file = codecs.open(target_file, 'w', encoding=ENCODE_METHOD)
  File "/home/lyd/anaconda3/lib/python3.8/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
OSError: [Errno 30] 只读文件系统:

**Comment by tzutalin** [comment]
Can you provide more information? Is it only happening yolo format?

`只读文件系统` sounds like your system problem.

**Comment by lyd959** [comment]
You can open the software. However, this problem occurs as soon as it is preserved. That's all the tips.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tzutalin/labelImg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月8日(星期六) 晚上10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tzutalin/labelImg] save problem (#746)





 
Can you provide more information? Is it only happening yolo format?
 
只读文件系统 sounds like your system problem.

**Comment by lyd959** [comment]
---Original---
From: ***@***.***&gt;
Date: Sun, May 9, 2021 02:16 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tzutalin/labelImg] save problem (#746)




 
Did you update some software or did you pull the latest code? I tried to reproduce on my Mac, and it works well.
 
Could you try to uninstall it and install it again
