### ISSUE TITLE
from lxml import etree ImportError: DLL load failed: The specified procedure could not be found. (Windows+ Anaconda)

### ISSUE THREAD

**Issue by haniehm** [tzutalin/labelImg#751]
I am facing this issue upon running:

python labelImg.py
Traceback (most recent call last):
  File "labelImg.py", line 43, in <module>
    from libs.labelFile import LabelFile, LabelFileError, LabelFileFormat
  File "C:\labelImage\libs\labelFile.py", line 10, in <module>
    from libs.pascal_voc_io import PascalVocWriter
  File "C:\labelImage\libs\pascal_voc_io.py", line 6, in <module>
    from lxml import etree
ImportError: DLL load failed: The specified procedure could not be found.

- **OS:** Windows 10 Enterprise
- **PyQt version:** 5.6.0

**Comment by haniehm** [comment]
This helped me to address the issue: 
https://stackoverflow.com/questions/54075542/lxml-installed-with-conda-importerror-dll-load-failed-the-specified-procedur
