### ISSUE TITLE
build-for-macOS script issue

### ISSUE THREAD

**Issue by ergoego** [tzutalin/labelImg#786]
Received this error when running the labelimg/build-tools/build-for-macOS.sh script:

```
macmini Deep Learning % sh build-labelimg-macos.sh 
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Tapping homebrew/cask
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 590002, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 590002 (delta 44), reused 61 (delta 28), pack-reused 589911
Receiving objects: 100% (590002/590002), 260.51 MiB | 1.46 MiB/s, done.
Resolving deltas: 100% (416862/416862), done.
Tapped 3918 casks (3,998 files, 279.4MB).
Warning: No available formula or cask with the name "python@2". Did you mean bpython, ipython, jython or cython?
==> Searching for similarly named formulae...
These similarly named formulae were found:
bpython             ipython             jython              cython
To install one of them, run (for example):
  brew install bpython
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
build-labelimg-macos.sh: line 4: pip: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6440k    0 6440k    0     0   830k      0 --:--:--  0:00:07 --:--:--  806k
Archive:  labelImg.zip
58406b578aaa1239d07b3ab1fb74c90a105dd9fb
   creating: labelImg-master/
   creating: labelImg-master/.github/
  inflating: labelImg-master/.github/no-response.yml  
  inflating: labelImg-master/.gitignore  
  inflating: labelImg-master/.travis.yml  
  inflating: labelImg-master/CONTRIBUTING.rst  
  inflating: labelImg-master/HISTORY.rst  
  inflating: labelImg-master/LICENSE  
  inflating: labelImg-master/MANIFEST.in  
  inflating: labelImg-master/Makefile  
  inflating: labelImg-master/README.rst  
 extracting: labelImg-master/__init__.py  
   creating: labelImg-master/build-tools/
  inflating: labelImg-master/build-tools/.gitignore  
  inflating: labelImg-master/build-tools/README.md  
  inflating: labelImg-master/build-tools/build-for-macos.sh  
  inflating: labelImg-master/build-tools/build-for-pypi.sh  
  inflating: labelImg-master/build-tools/build-ubuntu-binary.sh  
  inflating: labelImg-master/build-tools/build-windows-binary.sh  
  inflating: labelImg-master/build-tools/envsetup.sh  
  inflating: labelImg-master/build-tools/run-in-container.sh  
   creating: labelImg-master/data/
  inflating: labelImg-master/data/predefined_classes.txt  
   creating: labelImg-master/demo/
  inflating: labelImg-master/demo/demo.jpg  
  inflating: labelImg-master/demo/demo3.jpg  
  inflating: labelImg-master/demo/demo4.png  
  inflating: labelImg-master/demo/demo5.png  
  inflating: labelImg-master/issue_template.md  
  inflating: labelImg-master/labelImg.py  
   creating: labelImg-master/libs/
  inflating: labelImg-master/libs/__init__.py  
  inflating: labelImg-master/libs/canvas.py  
  inflating: labelImg-master/libs/colorDialog.py  
  inflating: labelImg-master/libs/combobox.py  
  inflating: labelImg-master/libs/constants.py  
  inflating: labelImg-master/libs/create_ml_io.py  
  inflating: labelImg-master/libs/hashableQListWidgetItem.py  
  inflating: labelImg-master/libs/labelDialog.py  
  inflating: labelImg-master/libs/labelFile.py  
  inflating: labelImg-master/libs/pascal_voc_io.py  
  inflating: labelImg-master/libs/settings.py  
  inflating: labelImg-master/libs/shape.py  
  inflating: labelImg-master/libs/stringBundle.py  
  inflating: labelImg-master/libs/toolBar.py  
  inflating: labelImg-master/libs/ustr.py  
  inflating: labelImg-master/libs/utils.py  
  inflating: labelImg-master/libs/yolo_io.py  
  inflating: labelImg-master/libs/zoomWidget.py  
   creating: labelImg-master/readme/
  inflating: labelImg-master/readme/README.jp.rst  
  inflating: labelImg-master/readme/README.zh.rst  
   creating: labelImg-master/requirements/
 extracting: labelImg-master/requirements/requirements-linux-python3.txt  
  inflating: labelImg-master/resources.qrc  
   creating: labelImg-master/resources/
   creating: labelImg-master/resources/icons/
 extracting: labelImg-master/resources/icons/app.icns  
  inflating: labelImg-master/resources/icons/app.png  
  inflating: labelImg-master/resources/icons/app.svg  
 extracting: labelImg-master/resources/icons/cancel.png  
 extracting: labelImg-master/resources/icons/close.png  
  inflating: labelImg-master/resources/icons/color.png  
 extracting: labelImg-master/resources/icons/color_line.png  
 extracting: labelImg-master/resources/icons/copy.png  
 extracting: labelImg-master/resources/icons/delete.png  
 extracting: labelImg-master/resources/icons/done.png  
  inflating: labelImg-master/resources/icons/done.svg  
 extracting: labelImg-master/resources/icons/edit.png  
 extracting: labelImg-master/resources/icons/expert1.png  
 extracting: labelImg-master/resources/icons/expert2.png  
  inflating: labelImg-master/resources/icons/eye.png  
 extracting: labelImg-master/resources/icons/feBlend-icon.png  
 extracting: labelImg-master/resources/icons/file.png  
 extracting: labelImg-master/resources/icons/fit-width.png  
 extracting: labelImg-master/resources/icons/fit-window.png  
 extracting: labelImg-master/resources/icons/fit.png  
  inflating: labelImg-master/resources/icons/format_createml.png  
 extracting: labelImg-master/resources/icons/format_voc.png  
 extracting: labelImg-master/resources/icons/format_yolo.png  
 extracting: labelImg-master/resources/icons/help.png  
 extracting: labelImg-master/resources/icons/labels.png  
  inflating: labelImg-master/resources/icons/labels.svg  
 extracting: labelImg-master/resources/icons/new.png  
  inflating: labelImg-master/resources/icons/next.png  
 extracting: labelImg-master/resources/icons/objects.png  
 extracting: labelImg-master/resources/icons/open.png  
  inflating: labelImg-master/resources/icons/open.svg  
  inflating: labelImg-master/resources/icons/prev.png  
 extracting: labelImg-master/resources/icons/quit.png  
 extracting: labelImg-master/resources/icons/resetall.png  
 extracting: labelImg-master/resources/icons/save-as.png  
  inflating: labelImg-master/resources/icons/save-as.svg  
 extracting: labelImg-master/resources/icons/save.png  
  inflating: labelImg-master/resources/icons/save.svg  
 extracting: labelImg-master/resources/icons/undo-cross.png  
 extracting: labelImg-master/resources/icons/undo.png  
 extracting: labelImg-master/resources/icons/verify.png  
 extracting: labelImg-master/resources/icons/zoom-in.png  
 extracting: labelImg-master/resources/icons/zoom-out.png  
 extracting: labelImg-master/resources/icons/zoom.png  
   creating: labelImg-master/resources/strings/
  inflating: labelImg-master/resources/strings/strings-ja-JP.properties  
  inflating: labelImg-master/resources/strings/strings-zh-CN.properties  
  inflating: labelImg-master/resources/strings/strings-zh-TW.properties  
  inflating: labelImg-master/resources/strings/strings.properties  
  inflating: labelImg-master/setup.cfg  
  inflating: labelImg-master/setup.py  
   creating: labelImg-master/tests/
 extracting: labelImg-master/tests/.gitignore  
  inflating: labelImg-master/tests/test.512.512.bmp  
  inflating: labelImg-master/tests/test_io.py  
  inflating: labelImg-master/tests/test_qt.py  
  inflating: labelImg-master/tests/test_settings.py  
  inflating: labelImg-master/tests/test_stringBundle.py  
  inflating: labelImg-master/tests/test_utils.py  
error:  cannot create labelImg-master/tests/?????.jpg
        Illegal byte sequence
   creating: labelImg-master/tools/
  inflating: labelImg-master/tools/README.md  
  inflating: labelImg-master/tools/label_to_csv.py  
build-labelimg-macos.sh: line 15: virtualenv: command not found
build-labelimg-macos.sh: line 16: /tmp/labelImgSetup/labelImg-py3/bin/activate: No such file or directory
```

- **OS:*macOS 12.0 Beta (21A5304g) & 11.5.2*
- **PyQt version:*N/A, separate error is thrown*

```
macmini Deep Learning % python3 -m pipenv run pip install pyqt5==5.14.0 lxml
Collecting pyqt5==5.14.0
  Using cached PyQt5-5.14.0.tar.gz (3.2 MB)
ERROR: pyqt5==5.14.0 from https://files.pythonhosted.org/packages/7c/5b/e760ec4f868cb77cee45b4554bf15d3fe6972176e89c4e3faac941213694/PyQt5-5.14.0.tar.gz#sha256=0145a6b7de15756366decb736c349a0cb510d706c83fda5b8cd9e0557bc1da72 has a pyproject.toml file that does not comply with PEP 518: 'build-system.requires' contains an invalid requirement: 'sip >=5.0.1 <6'
ego@egomacmini Deep Learning % python3 -m pipenv run pip install pyqt5==5.14.2 lxml
Collecting pyqt5==5.14.2
  Downloading PyQt5-5.14.2.tar.gz (3.2 MB)
     |████████████████████████████████| 3.2 MB 2.5 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ego/.local/share/virtualenvs/Deep_Learning-GfkQV9Qs/bin/python /Users/ego/.local/share/virtualenvs/Deep_Learning-GfkQV9Qs/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/dk/x9qrxpbj4jx25cmrv5q92h2r0000gn/T/tmp3r3abx6_
         cwd: /private/var/folders/dk/x9qrxpbj4jx25cmrv5q92h2r0000gn/T/pip-install-tb877z4w/pyqt5_8434ebc797f34b6cb42d01e8af9d8c75
    Complete output (29 lines):
    Traceback (most recent call last):
      File "/Users/ego/.local/share/virtualenvs/Deep_Learning-GfkQV9Qs/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 143, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/ego/.local/share/virtualenvs/Deep_Learning-GfkQV9Qs/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/Users/ego/.local/share/virtualenvs/Deep_Learning-GfkQV9Qs/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/ego/.local/share/virtualenvs/Deep_Learning-GfkQV9Qs/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 147, in prepare_metadata_for_build_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/private/var/folders/dk/x9qrxpbj4jx25cmrv5q92h2r0000gn/T/pip-build-env-84d21f6r/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/private/var/folders/dk/x9qrxpbj4jx25cmrv5q92h2r0000gn/T/pip-build-env-84d21f6r/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/private/var/folders/dk/x9qrxpbj4jx25cmrv5q92h2r0000gn/T/pip-build-env-84d21f6r/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 479, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 62, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/private/var/folders/dk/x9qrxpbj4jx25cmrv5q92h2r0000gn/T/pip-build-env-84d21f6r/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/private/var/folders/dk/x9qrxpbj4jx25cmrv5q92h2r0000gn/T/pip-build-env-84d21f6r/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 225, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/private/var/folders/dk/x9qrxpbj4jx25cmrv5q92h2r0000gn/T/pip-build-env-84d21f6r/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 66, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/4d/81/b9a66a28fb9a7bbeb60e266f06ebc4703e7e42b99e3609bf1b58ddd232b9/PyQt5-5.14.2.tar.gz#sha256=bd230c6fd699eabf1ceb51e13a8b79b74c00a80272c622427b80141a22269eb0 (from https://pypi.org/simple/pyqt5/) (requires-python:>=3.5). Command errored out with exit status 1: /Users/ego/.local/share/virtualenvs/Deep_Learning-GfkQV9Qs/bin/python /Users/ego/.local/share/virtualenvs/Deep_Learning-GfkQV9Qs/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/dk/x9qrxpbj4jx25cmrv5q92h2r0000gn/T/tmp3r3abx6_ Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyqt5==5.14.2 (from versions: 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4)
ERROR: No matching distribution found for pyqt5==5.14.2
```

Any help much appreciated, 

Erik

**Comment by ergoego** [comment]
Duplicate of [issue 790](https://github.com/tzutalin/labelImg/issues/790)
