### ISSUE TITLE
RUN ERROR

### ISSUE THREAD

**Issue by hanxiaoyuyu** [tzutalin/labelImg#81]
Traceback (most recent call last):
  File "./labelImg.py", line 28, in <module>
    import resources
  File "/home/zhangxuan/software/labelImg/resources.py", line 6315, in <module>
    qInitResources()
  File "/home/zhangxuan/software/labelImg/resources.py", line 6310, in qInitResources
    QtCore.qRegisterResourceData(0x01, qt_resource_struct, qt_resource_name, qt_resource_data)
TypeError: qRegisterResourceData(int, str, str, str): argument 2 has unexpected type 'str'

**Comment by hnVfly** [comment]
using pyrcc4 -py3 -o resources.py resources.qrc
