### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by PaVaNTrIpAtHi** [tzutalin/labelImg#837]
I was trying to open the labelimg annotator tool. it worked for the first time after installation but throws an error now. Would be glad if help is provided.

(labelimg) E:\labelImg-master>python labelImg.py
Traceback (most recent call last):
  File "labelImg.py", line 43, in <module>
    from libs.labelFile import LabelFile, LabelFileError, LabelFileFormat
  File "E:\labelImg-master\libs\labelFile.py", line 10, in <module>
    from libs.pascal_voc_io import PascalVocWriter
  File "E:\labelImg-master\libs\pascal_voc_io.py", line 6, in <module>
    from lxml import etree
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by PaVaNTrIpAtHi** [comment]
got it resolved.
first used try except for checking if i was able to import required package.
try:
  from lxml import etree
  print("running with lxml.etree !")
except ImportError:
  print("Import etree from lxml failed !")

got ("Import etree from lxml failed !")

then installed lxml using this
pip install lxml --force -U
and was able to run python labelImg.py
