### ISSUE TITLE
can't save xml in ubuntu 14.04

### ISSUE THREAD

**Issue by HeanJean** [tzutalin/labelImg#84]
My system is ubuntu 14.04.   I downloaded the prebuilt binaries, and run it  in terminal as root. but it can't save the xml. There are the tips:
***@***:~/Desktop/LabelImage/linux_v1.3.0$ sudo ./labelImg 
Unable to update the static FcBlanks: 0x0600
Unable to update the static FcBlanks: 0x0601
Unable to update the static FcBlanks: 0x0602
Unable to update the static FcBlanks: 0x0603
Unable to update the static FcBlanks: 0x06dd
Unable to update the static FcBlanks: 0x070f
Unable to update the static FcBlanks: 0x2028
Unable to update the static FcBlanks: 0x2029
Unable to update the static FcBlanks: 0xfff9
Unable to update the static FcBlanks: 0xfffa
Unable to update the static FcBlanks: 0xfffb
Cancel creation.
Traceback (most recent call last):
  File "labelImg/labelImg.py", line 1105, in saveFile
  File "labelImg/labelImg.py", line 1126, in _saveFile
  File "labelImg/labelImg.py", line 717, in saveLabels
UnicodeEncodeError: 'ascii' codec can't encode characters in position 72-75: ordinal not in range(128)
Traceback (most recent call last):
  File "labelImg/labelImg.py", line 1105, in saveFile
  File "labelImg/labelImg.py", line 1126, in _saveFile
  File "labelImg/labelImg.py", line 717, in saveLabels

**Comment by 91Eric** [comment]
hello, Do you solve the problem?I meet the problem in ubuntu16.04,thanks

**Comment by tzutalin** [comment]
Fix in the latest version
