### ISSUE TITLE
AssertionError: Missing string id : useDefaultLabel

### ISSUE THREAD

**Issue by pronoobkhan73** [tzutalin/labelImg#851]
labelImg>python labelImg.py
Traceback (most recent call last):
  File "C:\Users\Downloads\Compressed\labelImg\labelimg.py", line 1649, in <module>
    sys.exit(main())
  File "C:\Users\Downloads\Compressed\labelImg\labelimg.py", line 1645, in main
    app, _win = get_main_app(sys.argv)
  File "C:\Users\Downloads\Compressed\labelImg\labelimg.py", line 1636, in get_main_app
    win = MainWindow(args.image_dir,
  File "C:\Users\Downloads\Compressed\labelImg\labelimg.py", line 124, in __init__
    self.use_default_label_checkbox = QCheckBox(get_str('useDefaultLabel'))
  File "C:\Users\Downloads\Compressed\labelImg\labelimg.py", line 87, in <lambda>
    get_str = lambda str_id: self.string_bundle.get_string(str_id)
  File "C:\Users\Downloads\Compressed\labelImg\libs\stringBundle.py", line 47, in get_string
    assert(string_id in self.id_to_message), "Missing string id : " + string_id
AssertionError: Missing string id : useDefaultLabel.
- **OS: Windows 10**
- **PyQt version: 5**

**Comment by ahboon6945** [comment]
i have this issue also 

Traceback (most recent call last):
  File "labelImg.py", line 1649, in <module>
    sys.exit(main())
  File "labelImg.py", line 1645, in main
    app, _win = get_main_app(sys.argv)
  File "labelImg.py", line 1638, in get_main_app
    args.save_dir)
  File "labelImg.py", line 124, in __init__
    self.use_default_label_checkbox = QCheckBox(get_str('useDefaultLabel'))
  File "labelImg.py", line 87, in <lambda>
    get_str = lambda str_id: self.string_bundle.get_string(str_id)
  File "C:\Users\AHBOO\Documents\ObjectDetection\TFODCourse\Tensorflow\labelimg\libs\stringBundle.py", line 47, in get_string
    assert(string_id in self.id_to_message), "Missing string id : " + string_id
AssertionError: Missing string id : useDefaultLabel

OS : window 10
PyQt version: 5
using Jupyter notebook

**Comment by MaxPrinz** [comment]
Same for me :/ 

  File "labelImg.py", line 1649, in <module>
    sys.exit(main())
  File "labelImg.py", line 1645, in main
    app, _win = get_main_app(sys.argv)
  File "labelImg.py", line 1636, in get_main_app
    win = MainWindow(args.image_dir,
  File "labelImg.py", line 124, in __init__
    self.use_default_label_checkbox = QCheckBox(get_str('useDefaultLabel'))
  File "labelImg.py", line 87, in <lambda>
    get_str = lambda str_id: self.string_bundle.get_string(str_id)
  File "\libs\stringBundle.py", line 47, in get_string
    assert(string_id in self.id_to_message), "Missing string id : " + string_id
AssertionError: Missing string id : useDefaultLabel

OS: Windows 11
PyQT version 5

**Comment by ahboon6945** [comment]
Guys, there is an alternative way to execute it that don't required coding, follow this links : https://github.com/tzutalin/labelImg/releases/tag/v1.8.1 , just download extract and run the .exe files to run the labelling interface

**Comment by ni2508** [comment]
i am also getting the same error..

**Comment by ni2508** [comment]
@ahboon6945 which exe file you're talking about?

**Comment by ni2508** [comment]
Hey guys! I found the solution..
Refer this code: https://github.com/sulieman-kh/LabelImg , and don't have to change the code at 1114th line.

**Comment by pronoobkhan73** [comment]
> Guys, there is an alternative way to execute it that don't required coding, follow this links : https://github.com/tzutalin/labelImg/releases/tag/v1.8.1 , just download extract and run the .exe files to run the labelling interface

Thank you! it works for me

**Comment by junhua-zhang** [comment]
Add the following line in labelImg.py should work
from libs.resources import *

**Comment by tzutalin** [comment]
Hi I think it was a mistake caused by the previous pull request. I will revert the change

**Comment by tzutalin** [comment]
Fixed 
https://github.com/tzutalin/labelImg/commit/d685e50269387b5c5c0cb6c7d60725ae29244ee6
