### ISSUE TITLE
AssertionError: Missing string id : useDefaultLabel

### ISSUE THREAD

**Issue by RafCoder90** [tzutalin/labelImg#852]
- **OS: Ubuntu20.04 on vmware virtuale machine**
- **PyQt version: 5**

$python3 labelImg.py

Traceback (most recent call last):
  File "labelImg.py", line 1649, in <module>
    sys.exit(main())
  File "labelImg.py", line 1645, in main
    app, _win = get_main_app(sys.argv)
  File "labelImg.py", line 1636, in get_main_app
    win = MainWindow(args.image_dir,
  File "labelImg.py", line 124, in __init__
    self.use_default_label_checkbox = QCheckBox(get_str('useDefaultLabel'))
  File "labelImg.py", line 87, in <lambda>
    get_str = lambda str_id: self.string_bundle.get_string(str_id)
  File "/home/raff2590/Scrivania/raffaele/tensorflow_model/labelImg/libs/stringBundle.py", line 47, in get_string
    assert(string_id in self.id_to_message), "Missing string id : " + string_id

$make qt5p3 // But the error continue

Help me

**Comment by tzutalin** [comment]
Hello, 
Do you pull the latest code?

Supposedly, it  [was fixed ](https://github.com/tzutalin/labelImg/commit/d685e50269387b5c5c0cb6c7d60725ae29244ee6)
