### ISSUE TITLE
new version of labelimg does not read old version xml

### ISSUE THREAD

**Issue by AndreaPisoni** [tzutalin/labelImg#86]
Hi,

I have some xml I have annotated with the old labelimg version.

Now I have updated to the new version and I get this error:

AttributeError: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "labelImg/labelImg.py", line 614, in fileitemDoubleClicked
  File "labelImg/labelImg.py", line 875, in loadFile
  File "labelImg/labelImg.py", line 1224, in loadPascalXMLByFilename
  File "labelImg/libs/pascal_voc_io.py", line 132, in __init__
  File "labelImg/libs/pascal_voc_io.py", line 161, in parseXML
AttributeError: 'NoneType' object has no attribute 'text'

It seems the only difference between the new and the old xml is the "verified" bit on the first row. The new version should still be able to read xml without "verified" and add "verified=no" as default when verified is missing...

**Comment by CT-Yang** [comment]
Have a same question here, hope it can be fixed.

**Comment by CT-Yang** [comment]
HI
I find that you can download the version v1.2.3 to solve this problem.
After I doing this, I can open them successfully.

**Comment by tzutalin** [comment]
@AndreaPisoni ,
  I fixed it on the latest source code
