### ISSUE TITLE
macOS Monterey and anaconda crash

### ISSUE THREAD

**Issue by ricounet67** [tzutalin/labelImg#867]
- **OS:** macOS Monterey 12.3.1
- **PyQt version:** 5.12.3

I work with Anaconda and tried to install labelImg the same way that is explained for windows+Anaconda
Everithing seems to work but when I try to execute the program I have the following errors:
Traceback (most recent call last):
  File "/Users/ericleroy/GitHub/labelImg/labelImg.py", line 1660, in <module>
    sys.exit(main())
  File "/Users/ericleroy/GitHub/labelImg/labelImg.py", line 1656, in main
    app, _win = get_main_app(sys.argv)
  File "/Users/ericleroy/GitHub/labelImg/labelImg.py", line 1647, in get_main_app
    win = MainWindow(args.image_dir,
  File "/Users/ericleroy/GitHub/labelImg/labelImg.py", line 210, in __init__
    self.dock.setFeatures(self.dock.features() ^ self.dock_features)
TypeError: unsupported operand type(s) for ^: 'DockWidgetFeatures' and 'DockWidgetFeatures'
Do you have any idea?

**Comment by FranLucchini** [comment]
I have the exact same error, but in Windows 10 with conda

**Comment by khyll** [comment]
I also get the same error in Windows 10 with conda:

python 3.10.0
labelImg 1.8.6
pyqt5 5.12.3
lxml 4.8.0
