### ISSUE TITLE
no use for"pyrcc5 -o libs/resources.py resources.qrc",and then cannot use label img in yolo

### ISSUE THREAD

**Issue by jt647** [tzutalin/labelImg#871]
(yolo) D:\labelImg-master>conda install pyqt=5
Collecting package metadata (current_repodata.json): done
Solving environment: -
Warning: 8 possible package resolutions (only showing differing packages):
  - anaconda/noarch::certifi-2020.6.20-pyhd3eb1b0_3, anaconda/win-64::ca-certificates-2022.3.29-haa95532_1, anaconda/win-64::openssl-1.1.1n-h2bbff1b_0
  - anaconda/win-64::ca-certificates-2022.3.29-haa95532_1, anaconda/win-64::openssl-1.1.1n-h2bbff1b_0, defaults/noarch::certifi-2020.6.20-pyhd3eb1b0_3
  - anaconda/noarch::certifi-2020.6.20-pyhd3eb1b0_3, anaconda/win-64::openssl-1.1.1n-h2bbff1b_0, defaults/win-64::ca-certificates-2022.3.29-haa95532_1
  - anaconda/win-64::openssl-1.1.1n-h2bbff1b_0, defaults/noarch::certifi-2020.6.20-pyhd3eb1b0_3, defaults/win-64::ca-certificates-2022.3.29-haa95532_1
  - anaconda/noarch::certifi-2020.6.20-pyhd3eb1b0_3, defaults/win-64::ca-certificates-2022.3.29-haa95532_1, defaults/win-64::openssl-1.1.1n-h2bbff1b_0
  - defaults/noarch::certifi-2020.6.20-pyhd3eb1b0_3, defaults/win-64::ca-certificates-2022.3.29-haa95532_1, defaults/win-64::openssl-1.1.1n-h2bbff1b_0
  - anaconda/noarch::certifi-2020.6.20-pyhd3eb1b0_3, anaconda/win-64::ca-certificates-2022.3.29-haa95532_1, defaults/win-64::openssl-1.1.1n-h2bbff1b_0
  - anaconda/win-64::ca-certificates-2022.3.29-haa95532_1, defaults/noarch::certifi-2020.6.20-pyhd3eb1b0_3, defaults/win-64::openssl-1.1.1n-h2bbff1bdone

# All requested packages already installed.

(yolo) D:\labelImg-master>conda install -c anaconda lxml
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

**(yolo) D:\labelImg-master>pyrcc5 -o libs/resources.py resources.qrc**

(yolo) D:\labelImg-master>python labelImg.py
Traceback (most recent call last):
  File "D:\labelImg-master\labelImg.py", line 1660, in <module>
    sys.exit(main())
  File "D:\labelImg-master\labelImg.py", line 1656, in main
    app, _win = get_main_app(sys.argv)
  File "D:\labelImg-master\labelImg.py", line 1647, in get_main_app
    win = MainWindow(args.image_dir,
  File "D:\labelImg-master\labelImg.py", line 210, in __init__
    self.dock.setFeatures(self.dock.features() ^ self.dock_features)
**TypeError: unsupported operand type(s) for ^: 'DockWidgetFeatures' and 'DockWidgetFeatures'**

**Comment by jt647** [comment]
I ran “pyrcc5 -o libs/resources.py resources.qrc”but no resources.py exist in abelImg-master
