### ISSUE TITLE
"Missing string id : " + string_id AssertionError: Missing string id : lightWidgetTitle

### ISSUE THREAD

**Issue by rizki4106** [tzutalin/labelImg#897]
Hi i got this error when runing `python3 labelImg.py`

```text
"Missing string id : " + string_id
AssertionError: Missing string id : lightWidgetTitle
```
How do i solve this issue ?

**Comment by tzutalin** [comment]
Run make command again

**Comment by rizki4106** [comment]
Hi thank  you for your reply, but after i run that command i got another error
```text
TypeError: unsupported operand type(s) for ^: 'DockWidgetFeatures' and 'DockWidgetFeatures'
```

**Comment by tzutalin** [comment]
I think it is caused by the latest pull request.

The operator might be only available for python 3.8 or above.

what is your python version

**Comment by rizki4106** [comment]
i'am using python 3.10.4

**Comment by tzutalin** [comment]
Interesting , could you share the call stacks? It should be a easy fix

**Comment by rizki4106** [comment]
This error occur when i run `make` command

```text
pyrcc5 -o libs/resources.py resources.qrc
python3 -m unittest discover tests
...ERemove setting pkl file $/home/son/.labelImgSettings.pkl
...E..
======================================================================
ERROR: test_noop (test_qt.TestMainWindow)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/son/Ai/training/labelImg/tests/test_qt.py", line 13, in setUp
    self.app, self.win = get_main_app()
  File "/home/son/Ai/training/labelImg/labelImg.py", line 1686, in get_main_app
    win = MainWindow(args.image_dir,
  File "/home/son/Ai/training/labelImg/labelImg.py", line 213, in __init__
    self.dock.setFeatures(self.dock.features() ^ self.dock_features)
TypeError: unsupported operand type(s) for ^: 'DockWidgetFeatures' and 'DockWidgetFeatures'

======================================================================
ERROR: test_setInvaleLocaleToEnv_printErrorMsg (test_stringBundle.TestStringBundle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/son/Ai/training/labelImg/tests/test_stringBundle.py", line 18, in test_setInvaleLocaleToEnv_printErrorMsg
    prev_lc = os.environ['LC_ALL']
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LC_ALL'

----------------------------------------------------------------------
Ran 10 tests in 0.177s

FAILED (errors=2)
make: *** [Makefile:11: testpy3] Error 1
```

and when i run python3 labelImg.py here's the error

```text
File "/home/rizki/labelImg/labelImg.py", line 213, in __init__
    self.dock.setFeatures(self.dock.features() ^ self.dock_features)
TypeError: unsupported operand type(s) for ^: 'DockWidgetFeatures' and 'DockWidgetFeatures'
```

And you are right, this error occur when i pull from origin master yesterday

**Comment by tzutalin** [comment]
May I know what your qt version?

Could you try to reinstall your pyqt? I think it is about python QT version

Also, for your reference, you can follow the below instruction to install pyqt + python versions
https://github.com/tzutalin/labelImg/blob/master/.github/workflows/package.yml

**Comment by rizki4106** [comment]
Hi Thank you, after i follow these steps [https://github.com/tzutalin/labelImg/blob/master/.github/workflows/package.yml](https://github.com/tzutalin/labelImg/blob/master/.github/workflows/package.yml) it works, but after try to make rect box occur this error
```text
Traceback (most recent call last):
  File "/home/son/Ai/training/labelImg/labelImg.py", line 972, in new_shape
    text = self.label_dialog.pop_up(text=self.prev_label_text)
  File "/home/son/Ai/training/labelImg/libs/labelDialog.py", line 74, in pop_up
    offset += QPoint(btn.size().width()/4, btn.size().height()/2)
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 1 has unexpected type 'float'
  QPoint(QPoint): argument 1 has unexpected type 'float'
Aborted (core dumped)
```

After that I changed the code on file `libs/labelDialog.py` line `74`

from this
```python
offset += QPoint(btn.size().width()/4, btn.size().height()/2)
```
to this

```python
offset += QPoint(int(btn.size().width()/4), btn.size().height()/2)
```

and finally it's works
