### ISSUE TITLE
Clicking "Create RectBox" causes program to quit unexpectedly

### ISSUE THREAD

**Issue by Lanxiuyuzhou** [tzutalin/labelImg#912]
- **OS:** win11
- **PyQt5  version:** PyQt5                   5.15.7
- **PyQt5-Qt5 version:** PyQt5-Qt5               5.15.2
- **PyQt5-sip version:** PyQt5-sip               12.11.0
`Traceback (most recent call last):
  File "D:\PycharmProjects\yolov5-master\venv\lib\site-packages\libs\canvas.py", line 506, in paintEvent
    p.drawLine(self.prev_point.x(), 0, self.prev_point.x(), self.pixmap.height())
TypeError: arguments did not match any overloaded call:
  drawLine(self, QLineF): argument 1 has unexpected type 'float'
  drawLine(self, QLine): argument 1 has unexpected type 'float'
  drawLine(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'float'
  drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'float'`

**Comment by Lanxiuyuzhou** [comment]
Traceback (most recent call last):
  File "D:\PycharmProjects\yolov5-master\venv\lib\site-packages\libs\canvas.py", line 506, in paintEvent
    p.drawLine(self.prev_point.x(), 0, self.prev_point.x(), self.pixmap.height())
TypeError: arguments did not match any overloaded call:
  drawLine(self, QLineF): argument 1 has unexpected type 'float'
  drawLine(self, QLine): argument 1 has unexpected type 'float'
  drawLine(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'float'
  drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'float'

**Comment by matobodo** [comment]
duplicate with #885
