### ISSUE TITLE
Problem when installing it with docker

### ISSUE THREAD

**Issue by MariaLFreitas** [tzutalin/labelImg#963]
I did these steps:

- git clone repo
- docker pull tzutalin/py2qt4
- run the docker with the readme instructions
- inside the container `make qt4py2;./labelImg.py`

And I got that:
```
pyrcc4 -py2 -o libs/resources.py resources.qrc

Traceback (most recent call last):
  File "./labelImg.py", line 40, in <module>
    from libs.labelFile import LabelFile, LabelFileError, LabelFileFormat
  File "/home/labelImg/libs/labelFile.py", line 12, in <module>
    from libs.create_ml_io import CreateMLWriter
  File "/home/labelImg/libs/create_ml_io.py", line 4, in <module>
    from pathlib import Path
ImportError: No module named pathlib
```

What can I do to solve this? 

- **OS:** Ubuntu 22.04
- **PyQt version:**

**Comment by waldflaufer** [comment]
Hi @tzutalin 

I run into the same issue.

In addition: I am not listed as Sudo<br>
`ipfJC is not in the sudoers file.  This incident will be reported.`

**Comment by bkaangorur** [comment]
+1
