### ISSUE TITLE
BUG: GUI crashes for invalid label index

### ISSUE THREAD

**Issue by sohang3112** [tzutalin/labelImg#980]
In `classes.txt`, if 2 items are present, but the label annotation text for an image has an invalid index (eg. 4), then the program crashes due to `IndexError`. Instead of crashing, this error should be caught and shown in error popup in the GUI.

```
1062)], None, None, False)]
Traceback (most recent call last):
  File "C:\Users\SohangChopra\AppData\Local\Programs\Python\Python311\Lib\site-packages\labelImg\labelImg.py", line 1348, in open_prev_image
    self.load_file(filename)
  File "C:\Users\SohangChopra\AppData\Local\Programs\Python\Python311\Lib\site-packages\labelImg\labelImg.py", line 1111, in load_file
    self.show_bounding_box_from_annotation_file(file_path)
  File "C:\Users\SohangChopra\AppData\Local\Programs\Python\Python311\Lib\site-packages\labelImg\labelImg.py", line 1154, in show_bounding_box_from_annotation_file
    self.load_yolo_txt_by_filename(txt_path)
  File "C:\Users\SohangChopra\AppData\Local\Programs\Python\Python311\Lib\site-packages\labelImg\labelImg.py", line 1557, in load_yolo_txt_by_filename
    t_yolo_parse_reader = YoloReader(txt_path, self.image)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SohangChopra\AppData\Local\Programs\Python\Python311\Lib\site-packages\libs\yolo_io.py", line 112, in __init__
    self.parse_yolo_format()
  File "C:\Users\SohangChopra\AppData\Local\Programs\Python\Python311\Lib\site-packages\libs\yolo_io.py", line 143, in parse_yolo_format
    label, x_min, y_min, x_max, y_max = self.yolo_line_to_shape(class_index, x_center, y_center, w, h)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SohangChopra\AppData\Local\Programs\Python\Python311\Lib\site-packages\libs\yolo_io.py", line 125, in yolo_line_to_shape
    label = self.classes[int(class_index)]
            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

- **OS:** Windows 11
- **PyQt version:** 5.15.9
- **Python version:** 3.11

**Comment by gil938271** [comment]
isn't everything above 3.10 can not work because of the float to int bug?

**Comment by gil938271** [comment]
from 3.10

**Comment by sohang3112** [comment]
> float to int bug 

I don't know what you are referring to - can you please clarify?

**Comment by gil938271** [comment]
https://github.com/heartexlabs/labelImg/issues/938

**Comment by sohang3112** [comment]
So downgrading to version 1.8.1 should work on Windows, right?

**Comment by gil938271** [comment]
not sure i downgrade my python as you can see in the link the real problem is with qt

**Comment by gil938271** [comment]
its abandonware anyway I haven't got any comment in the last 6 days
