### ISSUE TITLE
No module named 'labelImg.labelImg'

### ISSUE THREAD

**Issue by Tobrux** [tzutalin/labelImg#997]
- **OS: Windows 10**
- **PyQt version: 5.15.9**

 I'm trying to run labelImg.exe from Powershell but when I do this error pops up:

`Traceback (most recent call last):`
 ` File "C:\Users\user\AppData\Local\Programs\Python\Python311\Scripts\labelImg-script.py", line 33, in <module>`
 `   sys.exit(load_entry_point('labelImg', 'console_scripts', 'labelImg')())`
 `            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
 ` File "C:\Users\user\AppData\Local\Programs\Python\Python311\Scripts\labelImg-script.py", line 25, in importlib_load_entry_point`
 `   return next(matches).load()`
 `          ^^^^^^^^^^^^^^^^^^^^`
 ` File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\importlib\metadata\__init__.py", line 202, in load`
 `   module = import_module(match.group('module'))`
 `            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
 ` File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module`
 `   return _bootstrap._gcd_import(name[level:], package, level)`
 `          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
 ` File "<frozen importlib._bootstrap>", line 1206, in _gcd_import`
 ` File "<frozen importlib._bootstrap>", line 1178, in _find_and_load`
 ` File "<frozen importlib._bootstrap>", line 1137, in _find_and_load_unlocked`
`ModuleNotFoundError: No module named 'labelImg.labelImg'; 'labelImg' is not a package`

Any idea what could be the problem?

**Comment by Jaihanumangranite** [comment]
[Italian Marble Suppliers in Delhi](https://www.jhgm.in/italian-marble.html)
[Indian Marble Suppliers](https://www.jhgm.in/indian-marble.html)
[Granite Slab Suppliers ](https://www.jhgm.in/granite-slab.html)
[Tiles Suppliers in Delhi](https://www.jhgm.in/tiles.html)
[Kota Marble Suppliers ](https://www.jhgm.in/kota-marble.html)
